version: '3.8'

services:

  demo:
    build:
      context: ../.. # root of the repo
      dockerfile: examples/gradio_threaded/Dockerfile
      args:
        APP_CONTEXT: examples/gradio_threaded
    volumes:
      # mounts models dir into container for reuse
      - $MODELS_PATH:/models
      # mounts agency source into container for development
      - ../..:/agency
    env_file: .env
    environment:
      LOGLEVEL: # pass through
      TRANSFORMERS_CACHE: /models/transformers_cache
    profiles: [threaded]
    ports:
      - '$WEB_APP_PORT:8080'
    # socat is used to redirect from the hardcoded ip:port in gradio's dev mode
    # https://github.com/gradio-app/gradio/issues/3656
    command: |
      bash -ce "
        socat TCP-LISTEN:8080,fork,reuseaddr TCP:127.0.0.1:7860 &
        echo \"Launching gradio app at http://localhost:$WEB_APP_PORT\. Please wait...\"
        poetry run python demo_threaded.py | grep -v \"Launching.*127.0.0.1:7860\"
      "
    tty: true
    stdin_open: true
