source "https://rubygems.org"

# jekyll plugins
group :jekyll_plugins do
  gem "github-pages" # automatically requires the following commented gems
  # gem "jekyll"
  # gem "jekyll-feed"
  # gem "jekyll-seo-tag"
  # gem "jekyll-sitemap"
end

# jekyll theme
gem "just-the-docs"

# local dev server
gem "webrick", "~> 1.8"
