source "https://rubygems.org"

# jekyll plugins
gem "github-pages" # automatically requires the "jekyll" gem
gem "jekyll-feed", "~> 0.12"

# jekyll theme
gem "just-the-docs"

# local dev server
gem "webrick", "~> 1.8"
