version: '3.8'

# shared config for the main demo container and chatty
x-demo-base:
  &demo-base
  build:
    context: ../.. # root of the repo
    dockerfile: examples/demo/Dockerfile
  volumes:
    # mounts models dir into container for reuse
    - $MODELS_PATH:/models
    # mounts source into container for development
    - ../..:/agency
  env_file: .env
  environment:
    TRANSFORMERS_CACHE: /models/transformers_cache

services:

  native:
    <<: *demo-base
    ports:
      - '$WEB_APP_PORT:$WEB_APP_PORT'
    command: poetry run python native_demo.py
    tty: true
    stdin_open: true

  amqp:
    <<: *demo-base
    depends_on:
      - rabbitmq
      - amqp_2
    ports:
      - '$WEB_APP_PORT:$WEB_APP_PORT'
    command: poetry run python amqp_demo_1.py
    tty: true
    stdin_open: true

  amqp_2:
    <<: *demo-base
    depends_on:
      - rabbitmq
    command: poetry run python amqp_demo_2.py

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672 # broker
      - 15672:15672 # management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
