version: '3.8'


# Shared config for all containers
x-demo-base:
  &demo-base
  build:
    context: ../.. # root of the repo
    dockerfile: examples/demo/Dockerfile
  volumes:
    # mounts models dir into container for reuse
    - $MODELS_PATH:/models
    # mounts source into container for development
    - ../..:/agency
  env_file: .env
  environment:
    LOGLEVEL: # pass through
    LOG_PYGMENTS_STYLE: # pass through
    TRANSFORMERS_CACHE: /models/transformers_cache


services:

  # This container demonstrates using a LocalSpace
  local:
    <<: *demo-base
    profiles: [local]
    ports:
      - '$WEB_APP_PORT:8080'
    # socat is used to redirect from the hardcoded ip:port in gradio's dev mode
    # https://github.com/gradio-app/gradio/issues/3656
    command: |
      bash -ce "
        poetry run python demo_local.py
      "
    tty: true
    stdin_open: true

  # This container demonstrates using an AMQPSpace
  amqp:
    <<: *demo-base
    profiles: [amqp]
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '$WEB_APP_PORT:8080'
    command: |
      bash -ce "
        poetry run python demo_amqp.py
      "
    tty: true
    stdin_open: true

  rabbitmq:
    profiles: [amqp]
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672 # broker
      - 15672:15672 # management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 3s
      timeout: 5s
      retries: 10
