version: '3.8'


services:

  main:
    build:
      context: .. # root of the repo
      dockerfile: demo/Dockerfile
    volumes:
      # mounts models dir into container for reuse
      - $MODELS_PATH:/models
      # mounts source into container for development
      - ..:/agency
    env_file: .env
    environment:
      APP_ENV: development
      LOGLEVEL: # pass through
      TRANSFORMERS_CACHE: /models/transformers_cache
    ports:
      - '$WEB_APP_PORT:8080'
    command: poetry run python main.py
    tty: true
    stdin_open: true
