version: '3.8'

services:
  rabbitmq:
    container_name: RabbitMQ-MQTT
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672 # broker
      - 15672:15672 # management
      - 1883:1883 # mqtt
      - 15675:15675 # web mqtt
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
        /bin/bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt; rabbitmq-server"