name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install dependencies
      run: npm install @iarna/toml

    - name: Check for version changes
      id: check_version
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const execSync = require('child_process').execSync;
          const toml = require('@iarna/toml');
          const current = fs.readFileSync('pyproject.toml', 'utf8');
          execSync('git fetch origin main:main');
          execSync('git checkout main pyproject.toml');
          const previous = fs.readFileSync('pyproject.toml', 'utf8');
          execSync('git checkout HEAD pyproject.toml');
          const currentVersion = toml.parse(current).tool.poetry.version;
          const previousVersion = toml.parse(previous).tool.poetry.version;
          const result = currentVersion !== previousVersion;
          console.log(`\n${result} = (${currentVersion}) !== (${previousVersion})`);
          return result;

    - name: Build and publish (dry run)
      if: steps.check_version.outputs.result == 'true'
      run: |
        echo "Dry run: Building and publishing package with Poetry"

        # TODO Uncomment the following lines to actually build and publish the package
        # poetry build
        # poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}

    # TODO Uncomment the following as well when ready
    # - name: Create tag
    #   if: steps.check_version.outputs.result == 'true'
    #   uses: mathieudutour/github-tag-action@v6.1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
