name: tests

on:
  push:
    branches:
      - main
      - build # temp
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: { python-version: 3.9 }
    - name: Install development dependencies
      run: |
        ls -l
        python -m pip install --upgrade pip
        pip install -r requirement-dev.txt
    - run: python -m unittest discover tests
